### ISSUE TITLE
Error al importar `validateRut`

### ISSUE THREAD

**Issue by nxtvoid** [cristiansantana/chile-rut#2]
Al importar algun metodo en `Next.js  v14.2.4`, recibo el siguiente error:

```shell
Module not found: Can't resolve '@cristiansantana/chile-rut/'
```

Para solucionarlo tuve que hacer lo siguiente:

```jsx
import { validateRut } from '@cristiansantana/chile-rut/dist/src'
```
---

Consultas:
1. El paquete esta funcionando?
2. Valida correctamente el Rut o quedo incompleto?
3. Lo seguirás manteniendo?

**Comment by cristiansantana** [comment]
Hola @JJozef . He revisado lo que indicas, efectivamente veo el mismo problema que tú. Lo corregiré y actualizaré.

Respondiendo a tus preguntas:

1.- El paquete esta funcionando?
Sí
2.- Valida correctamente el Rut o quedo incompleto?
Valida correctamente
3.- Lo seguirás manteniendo?
Sí

**Comment by nxtvoid** [comment]
Vale, muchas gracias, muy buena utilidad!

**Comment by cristiansantana** [comment]
Resuelto el problema. La versión 1.0.8 incorpora la corrección. Gracias @JJozef  por tu observación.
